### ISSUE TITLE
[Adobe XD] known to-do enhancements

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-design-kit#497]
## Adobe Xd kit

We need to add the following things to the Adobe Xd kits:

-------

**Breadcrumb**
- [ ] Add states for overflow

**Button**
- [ ] Add 2x large (80px) button (no icon only variant)
- [ ] Add extra large (64px) button (no icon only variant)

**Checkbox**
- [ ] Update focus states to be straight 

**Contained list**
- [ ] [See Figma issue](https://github.com/carbon-design-system/carbon-design-kit/issues/567)

**Content switcher**
- [ ] Update visual styling

**Data table**
- [ ] Add Medium (40px) height 
- [ ] Update focus states to be straight and to be the correct size

**Link**
- [ ] Add Large and Small sizes
- [ ] Add link with icon variant for all sizes

**Notification** (v11 priority)
- [ ] Make v11 updates

**Number input**
- [ ] Update visual styling

**Overflow menu**
- [ ] Add Large (48px) and Small (32px) sizes

**Pagination**
- [ ] Add Medium (40px) and Small (32px) sizes

**Popover**(v11 priority)
- [x] Add v11 component

**Progress bar**
- [x] Add v11 component https://github.com/carbon-design-system/carbon-design-kit/issues/504

**Progress indicator**
- [ ] Update visual styling of icons

**Radio button**
- [ ] Update focus states to have 1px space between icon and focus border

**Structured list**
- [ ] Remove icon on hover
- [ ] Add simple variant
- [ ] Add flush alignments 

**Tabs**(v11 priority)
- [x] #522

**Tag**
- [ ] Add small tag size
- [ ] Add outline tag style
- [ ] Update focus to only be on close icon for filterable tags
- [ ] Update hover and focus for filterable tags to be flush to tag, not inset.

**Tile**
- [x] Add multi-select variant

**Toggletip**(v11 priority)
- [ ] Add v11 component

**Tooltip**(v11 priority)
- [ ] Make v11 updates

**Comment by laurenmrice** [comment]
Closing as we are no longer supporting our Adobe XD libraries
