### ISSUE TITLE
[Figma] Data table: Missing radio selection type

### ISSUE THREAD

**Issue by silvio-hajdin** [carbon-design-system/carbon-design-kit#500]
## Detailed description

This may have been discussed/addressed in the past, and if so please point to the issue(s) or related discussions. Otherwise, given the frequent occurrence and need in our designs, I'd like to request addition of the 5th, 'Radio selection' table type (for many real-life product situations where we only can have, and proceed with the single selection out of multiple (potentially many) choices. This use case is also defined in the [Carbon components definitions](https://www.carbondesignsystem.com/components/data-table/usage/#radio-selection).

There are of course 'detachable' and also 'overriding' ways to massage the existing data table component in Figma but this rapidly becomes a time drain with larger tables and multiple occurrences/variants, and can be a huge time-saver if implemented at the component/variant level. Thanks!

## Additional information

![image](https://user-images.githubusercontent.com/98415805/161262151-14b382ab-33c3-4bd1-84ac-e9ea16a9fdaf.png)

--------
_Planning content for Carbon team_

## Tasks

**v10** 
- [x] White theme  (Main)
- [x] Gray 10 theme (Main) 
- [x] Gray 90 theme (Branch)
- [x] Gray 100 theme (Branch)

**v11** Priority 
- [x] White theme

**Comment by laurenmrice** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/System-Squad-593830641344b813db10934d/issues/carbon-design-system/carbon-design-kit/500?planning-poker) with ZenHub @aagonzales @thyhmdo

**Comment by aagonzales** [comment]
Looks like this has been completed and added to the libraries
