### ISSUE TITLE
[Figma] V11 Migration

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#502]
# PHASE 1

- [x] Duplicate `White theme - v11` branch as new file. 

## IBM Design Language - Colors

- [x] https://github.com/carbon-design-system/carbon-design-kit/issues/498 - Jules
- [x] https://github.com/carbon-design-system/carbon-design-kit/issues/508 - Jules

## Carbon themes: Styles
- [x] https://github.com/carbon-design-system/carbon-design-kit/issues/509 - Lauren
- [x] https://github.com/carbon-design-system/carbon-design-kit/issues/510 - Anna
- [x] https://github.com/carbon-design-system/carbon-design-kit/issues/521
- [x] Create v11 text styles library

## Carbon themes: Components

- [x] https://github.com/carbon-design-system/carbon-design-kit/issues/511 
   - [x] White theme
   - [x] Reviewed
- [x] https://github.com/carbon-design-system/carbon-design-kit/issues/512
   - [x] White theme
   - [x] Reviewed
- [x] https://github.com/carbon-design-system/carbon-design-kit/issues/513 
   - [x] White theme
   - [x] Reviewed
- [x] https://github.com/carbon-design-system/carbon-design-kit/issues/514 - **IN REVIEW**
   - [x] White theme
   - [x] Reviewed
- [x] https://github.com/carbon-design-system/carbon-design-kit/issues/515
   - [x] White theme
   - [x] Reviewed
- [x] https://github.com/carbon-design-system/carbon-design-kit/issues/516
   - [x] White theme
   - [x] Reviewed
- [x] https://github.com/carbon-design-system/carbon-design-kit/issues/517 
   - [x] White theme
   - [x] Reviewed
- [x] https://github.com/carbon-design-system/carbon-design-kit/issues/492 
   - [x] White theme
   - [x] Reviewed

### New issues from QA
- [x] https://github.com/carbon-design-system/carbon-design-kit/issues/538
- [x] https://github.com/carbon-design-system/carbon-design-kit/issues/540

## QA
- [x] **Color token values:** Check all tokens values match updates in v11, see [element preview](https://carbon-elements.netlify.app/themes/examples/preview-v11/). 
- [x] **Color tokens application:** QA all components to make sure they are now using the correct v11 token as some v10 tokens have been split into multiple v11 tokens. See component style tabs
- [x] **Type tokens:** make sure file is pulling from the new v11 IDL library
- [x] [Variant size names](https://github.com/carbon-design-system/carbon-design-kit/issues/535): QA all the components to make sure they are using the correct v11 [size names](https://carbondesignsystem.com/migrating/guide/design#sizing-breaking) (we might have already done this in the first figma round). See component style tabs for specifics if unsure.
- [x] **Main branch updates** Make sure all updates from 'main' "v10" library have been updated in v11 library as well

# PHASE 2

## Duplicate & update
After all of the phase 1 tasks have been completed and close, we will duplicate the v11 White theme to create new G10, G90, G100 theme files

**Color tokens**
- https://github.com/carbon-design-system/carbon-design-kit/issues/543
- [x] Update colors tokens values in the Gray 10 theme
- [x] Update colors tokens values in the Gray 90 theme
- [x] Update colors tokens values in the Gray 100 theme

**Effect styles**
- https://github.com/carbon-design-system/carbon-design-kit/issues/543
- [x] Update effect style values in the Gray 10 theme
- [x] Update effect style values in the Gray 90 theme
- [x] Update effect style values in the Gray 100 theme

## Rename files
- [x] Rename the original files to be `v10`
- [x] Update cover artwork so its distinguishable from `v11` at a glance 
- [x] Update read me pages to include information about versioning

## Publish
- [x] Publish v11 libraries
- [x] Update links and documentation on the website
- [x] Send Slack announcement

**Comment by aagonzales** [comment]
![Uploading figma+carbon.png…]()

**Comment by aagonzales** [comment]
We have published a v11-beta for all four themes to the internal IBM Figma org. This epic is now considered done. 

We will release the v11 Figma libraries publically (externally) at a TBD date after we stabilize all Figma enhancements.
