### ISSUE TITLE
[Sketch] Add "Fluid inputs"

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#558]
Fluid inputs: Provide design tooling updates for all inputs to `v11` Sketch kit
Add your name beside the component when you start working on it.

```[tasklist]
### Components
- [x] https://github.com/carbon-design-system/carbon-design-kit/issues/620
- [x] https://github.com/carbon-design-system/carbon-design-kit/issues/624
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/625
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/626
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/627
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/628
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/629
- [x] https://github.com/carbon-design-system/carbon-design-kit/issues/623
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/630
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/622
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/631
```

This has an exact effort of `33` or a planning effort of `40`
