### ISSUE TITLE
[Figma] Bring v11 kit to stable

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#566]
**Tasks**
- [x] [[Figma] v11 Component enhancements](https://github.com/carbon-design-system/carbon-design-kit/issues/565) 
- [x] [New illustrations for cover.](https://github.com/carbon-design-system/carbon-design-kit/issues/573) 
  - [x] Update covers per library.
- [x] Remove all status dots for components.
- [x] Rename libraries to `(v11)` instead of (v11 BETA) in the files and on the team space.
- [x] Delete deprecated team space.
- [x] Publish stable v11 kits internally.
- [x] Publish stable v11 kits externally (including v11 Text styles and v11 Hover Color Styles).

**Comms**
- [x] [Slack announcement ](https://ibm.box.com/s/vbs1a8qtf1rmq5d84be7z4efwkxj5xtl) 
  - [x] Post with slack block kit.
- [x] [Update website with GA release](https://github.com/carbon-design-system/carbon-website/issues/3175)

**Comment by thyhmdo** [comment]
[New illustrations covers ](https://github.com/carbon-design-system/carbon-design-kit/issues/573)
May need review

**Comment by laurenmrice** [comment]
v11 GA release has been published ✅
