### ISSUE TITLE
[Sketch] Field validation errors: CheckboxGroup updates

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon-design-kit#593]
- [x] Wait until [design spec](https://github.com/carbon-design-system/carbon/issues/12861) is done to size

```[tasklist]
### Tasks
- [ ] Add to all 4 themes
- [ ] Add `invalid` state to *single Checkbox*
- [ ] Add `invalid` state to *Checkbox group*
- [ ] Add `warning` state to *single Checkbox*
- [ ] Add `warning` state to *Checkbox group*
- [ ] Add `helper text` state to *single Checkbox*
- [ ] Add `helper text` state to *Checkbox group*
```

**Comment by aagonzales** [comment]
Sketch is now entering maintenance mode and will no longer have parity with Figma

**Comment by laurenmrice** [comment]
We are no longer maintaining our Sketch libraries in favor of our [Figma libraries](https://carbondesignsystem.com/designing/kits/figma/), so we will be closing this issue.
