### ISSUE TITLE
[Figma] Creating the image guideline production

### ISSUE THREAD

**Issue by thyhmdo** [carbon-design-system/carbon-design-kit#602]
### Overview

Creating the Figma file for Image production guideline from the original Sketch file. 
https://carbondesignsystem.com/designing/design-resources/#image-production-guidelines

Working file: https://www.figma.com/file/XQqHxu38CiY3Vx1iHdafIa/Carbon-Image-production-guidelines_WIP?node-id=48%3A8262&t=G5Y4uMblIcA14d1p-1

### Phase 1: The basics

```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/633
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/634
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/664
```

### Phase 2: Review + Update the guidance 

```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/635
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/667
```

### Phase 3: Create + Review the components

```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/641
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/642
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/644
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/645
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/672
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/661
```

### Phase 4: Comms

```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/671
```
