### ISSUE TITLE
[Tile] Update text size for consistency and avoid confusion

### ISSUE THREAD

**Issue by thyhmdo** [carbon-design-system/carbon-design-kit#692]
### Acceptance criteria

- The community was confused about the inconsistency of text sizes in code and Figma kit. The intention is to let the product teams decide the text sizes. 
[Ref Slack discussion](https://ibm-studios.slack.com/archives/C0M053VPT/p1686168853280719
)

---

### To-do
- [x] Set the text size to `body-compact-01` so that it's consistent with the code in Storybook.
- [x] Checkmark icon: Set this to boolean and hide it. **⤵️**
   >This functionality is already attainable through an existing dropdown that allows users to choose between various types such as Clickable, Single-select, Multi-select, etc.
- [x] Checkmark icon: Pin to the right side of tiles.

---
### Review
- [x] Carbon Review (carbon designer)
- [x] Figma review (figma expert/Juan)
