### ISSUE TITLE
Figma: deprecate theme libraries

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-design-kit#700]
This is the umbrella issue for deprecating the Carbon theme libraries in Figma, in favor of keeping the White theme library  (Renaming to "All themes") and implementing the theming variable feature that was released during the Config conference. 

```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/704
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/710
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3644
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/706
- [x] Publish Figma library and Website doc updates
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/712
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3653
```
