### ISSUE TITLE
[Data table] Increase Column Amount

### ISSUE THREAD

**Issue by simongranthamibm** [carbon-design-system/carbon-design-kit#717]
### Acceptance criteria

- There are many cases where a data table requires more than 8 columns. This is a request to increase the amount of columns available in the data table component in Figma to at least 12. This would save a tremendous amount of manual labor required to add and merge in additional columns.  

**To-do**
- [x] Add at least 12 columns inside of data table to be turned on/off by the user.
- [x] Carbon review (carbon designer)
- [x] Figma review (figma expert/Juan)

**Comment by alina-jacob-ibm** [comment]
Note: This was requested in the first Figma Office Hours of 2024 as well.

**Comment by thyhmdo** [comment]
Added 4 more row cell items for Headers and rows, the total is now 12. 

@simongranthamibm We will need to see a specific use case to consider adding more than 12 columns. You can provide design examples or screenshots

**Comment by thyhmdo** [comment]
@simongranthamibm Right, sorry for the confusion, I was just referring to the individual item's name

![image](https://github.com/carbon-design-system/carbon-design-kit/assets/77697351/46788e38-16f6-4a9d-9743-6e4793e46a4a)

**Comment by simongranthamibm** [comment]
Ok great, thanks @thyhmdo . 12 columns should be sufficient for me!
