### ISSUE TITLE
[Status icons] add high, medium, and low attention icons to kit

### ISSUE THREAD

**Issue by thyhmdo** [carbon-design-system/carbon-design-kit#732]
## Acceptance criteria
- We need to add the high, medium, and low attention status icons based on the [Status indicators Pattern](https://carbondesignsystem.com/patterns/status-indicator-pattern/#choosing-for-context) to the v11 All Themes Figma Kit in the [Utilities section](https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/(v11)-All-themes---Carbon-Design-System?type=design&node-id=42789%3A39468&mode=design&t=6GGpesOmdnjZ20vv-1). Currently, we only have these 6 icons in Utilities. 

<img width="569" alt="image" src="https://github.com/carbon-design-system/carbon-design-kit/assets/77697351/2c3b2aea-5911-44b4-8eb7-2ac927360e44">

---

### To-do
- [x]  Use this [existing Figma branch](https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/branch/S0iSsNU4hKqAaTB3K3yRGe/(v11)-All-themes---Carbon-Design-System?type=design&node-id=1768%3A1441&mode=design&t=6JR5LE6IccpddSTt-1) to add icons to Utilities section in the v11 All Themes Figma kit. There is a checklist below in this issue.
  - Note: With these additions of icons we may need to adjust the naming convention of some of the existing icons in utilities to have a better naming structure.
  
### Review
- [x] Carbon review (carbon designer)
- [ ] Figma review (figma expert/Juan)

----

## Add High attention icons

<img width="1118" alt="High attention" src="https://github.com/carbon-design-system/carbon-design-kit/assets/43969356/4d953ee6-67e2-4b09-9a9c-a703afae10ae">

**Failure**
- [x] Error--filled
- [x] Error

**Warning**
- [x] Warning--filled
- [x] Warning

**Warning alt**
- [x] Warning--hex--filled
- [x] Warning--hex

**Misuse**
- [x] Close--filled
- [x] Close--outline

**Caution major**
- [x] Warning--alt-inverted--filled
- [x] Warning--alt-inverted

**Caution minor**
- [x] Warning--alt--filled
  - [x] Light theme
  - [x] Dark theme
- [x] Warning--alt

## Add Medium attention icons

<img width="1118" alt="Medium attention" src="https://github.com/carbon-design-system/carbon-design-kit/assets/43969356/3dfac8b6-0ac0-46f7-87d9-cd52eefd8934">

 **Undefined**
- [x] Undefined--filled
- [x] Undefined

**Normal**
- [x] Checkmark--filled
- [x] Checkmark--outline

**Normal-alt**
- [x] Checkmark

**Success**
- [x] Checkmark--filled
- [x] Checkmark--outline

**In progress**
- [x] In-progress

**Incomplete**
- [x] Incomplete

**Not started**
- [x] Circle-dash

**Pending**
- [x] Pending-filled
- [x] Pending

## Add Low attention icons

<img width="1118" alt="Low attention" src="https://github.com/carbon-design-system/carbon-design-kit/assets/43969356/85b3c660-cb0b-42ff-8e32-efaa5fe03c18">

**Unknown**
- [x] Unknown--filled
- [x] Unknown

**Help**
- [x] Help--filled
- [x] Help

**Information**
- [x] Information--filled
- [x] Information

**Information-alt**
- [x] Information--square--filled
- [x] Information--square

-----

**Comment by sstrubberg** [comment]
what icons need to be added to the kit? (hit list, audit)
stroke for accessibility?
do the work to make them status indicators in code?

**Comment by aubrey-oneal** [comment]
In a design crit we discussed the disparate names for status icons. Next steps:

Conduct an audit with columns for 1. Code name if it exists 2. Website doc name 3. Figma name

Align on which name we will use before sending this to review.

**Comment by aubrey-oneal** [comment]
[Naming audit airtable](https://airtable.com/app8E3u3LlUbMNVwt/tblvAZwRc3KdGHZqO/viwKP8PIBayWSwa5y?blocks=hide)
