### ISSUE TITLE
Inline dropdown: label doesn't exist in Figma kit

### ISSUE THREAD

**Issue by janhassel** [carbon-design-system/carbon-design-kit#741]
## Acceptance criteria

- In the Figma v11 All Themes kit, the Dropdown inline component doesn't support a label when the inline variant is being used. There should be an option to show the label.

<img width="512" alt="image" src="https://github.com/carbon-design-system/carbon-design-kit/assets/28265588/4494d6e8-5402-457a-81c6-5594f68d1f5b">

The [coded component](https://react.carbondesignsystem.com/?path=/story/components-dropdown--inline) offers such a label.
<img width="314" alt="image" src="https://github.com/carbon-design-system/carbon-design-kit/assets/28265588/1393bda2-0c4d-4e21-b5dd-9848466d94b2">

--- 

**To-do**
- [x] Add the option for a label next to the inline dropdown. The label should be `$body-compact-01` in this case.
- [x] Figma review (figma expert/Juan)
- [x] Carbon review (carbon designer)

**Comment by alina-jacob** [comment]
Hi @janhassel this is now fixed in the Figma Kit, thanks!
