### ISSUE TITLE
Dividers in components: Update Figma Kit

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-design-kit#745]
## Acceptance criteria

- Update the v11 All themes Figma kit to reflect the changes that came out of the [final design solutions](https://github.com/carbon-design-system/carbon/issues/15286) for dividers in components.

---

**Tasks**
- [x] Confirm the Divider Specs
- [x] Introduce Fluid State for Filterable Multi-select
- [x] Introduce Dividers across multiple states for Combo box (Default and Fluid)
- [x] Introduce Dividers across multiple states for Filterable Multi-select (Default and Fluid)
- [x] Remove vertical divider from the Fluid Search component
- [x] Carbon review (carbon designer)
- [x] Figma review (figma expert/Juan)

**Comment by tay1orjones** [comment]
@alina-jacob-ibm @laurenmrice Some further slug/ordering details that I think need incorporated to the design spec: https://ibm-studios.slack.com/archives/GCQ5R263T/p1706199005227399

> The status indicators are the exception to the slug always appearing on the left. The order should be Status indicator > Slug > other elements
>
> ![image](https://github.com/carbon-design-system/carbon-design-kit/assets/3360588/c182c130-733b-419f-87ac-04b6b400d6ce)

**Comment by alina-jacob-ibm** [comment]
Hi @tay1orjones, following up on the comment above, the order mentioned above is correct and all Design specs are created to reflect the same ✅️ 

The order should be **_Status indicator > Slug > other elements_**
Also pasting a screenshot with various examples for Visual Reference

![Dividers in Carbon Components (Input fields)](https://github.com/carbon-design-system/carbon-design-kit/assets/148988115/6d2acd15-7d50-4cfa-8647-6367592da432)
