### ISSUE TITLE
[Figma] add modal inline loading

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-design-kit#746]
## Acceptance criteria

- Add modal inline loading to the v11 All themes Figma kit. We already have an [open Figma branch](https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/branch/AVpfa69OJr8rfr61JZkDw5/(v11)-All-themes---Carbon-Design-System?type=design&node-id=370%3A0&mode=design&t=cmS8hwx1NzdSfJGE-1) for this.
- Ref: [Final specs](https://github.com/carbon-design-system/carbon/issues/10495#issuecomment-1674614130) from our contirbutors in this issue

![Inline loader_white](https://github.com/carbon-design-system/carbon/assets/135205291/62d1aa49-6c28-46f6-b5ac-fc9ad96ae35b)

![Inline loader_grey](https://github.com/carbon-design-system/carbon/assets/135205291/ced38669-5b40-4e13-bad3-c2102d409113)

---

**To-do**
- [ ] Add to v11 All themes Figma kit

**Review**
- [ ] Carbon review (carbon designer) 
- [ ] Figma review (figma expert/juan)
