### ISSUE TITLE
Fixing Hover and subsequent Interactions for Dropdown Menu Items in Figma Kit

### ISSUE THREAD

**Issue by alina-jacob-ibm** [carbon-design-system/carbon-design-kit#747]
## Detailed description

This bug is related to the Menu Items of the Dropdown family consisting of Dropdown, Combobox, Multiselect and Filterable Multiselect. 

Upon Hovering a Menu item of a drop down, the Horizontal Divider shouldn't be visible. 
Image A: shows Figma Hover, Selected and Hover + Selected states
Image B: shows React Hover, Selected and Hover + Selected

![Dropdown menu item hover state horizontal divider bug](https://github.com/carbon-design-system/carbon-design-kit/assets/148988115/2fa02f18-646a-4ec5-a564-63ee7eca104f)
**_Image B, is the correct representation. The following needs to be reflected and updated in the Figma kit as well._**

> What version of the Carbon Design System Kit are you using?
V11 All Theme

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.
Dropdown family consisting of Dropdown, Combobox, Multiselect and Filterable Multiselect. 
(Specifically for Hover, Selected and Hover + Selected states)

> What did you expect to happen? What happened instead? What would you like to see changed?
Image B (pasted above), is the correct representation and the following needs to be reflected and updated in the Figma kit.

> Is this issue being filed based on a discrepancy between the website/code and the kit? If so what is the inconsistency?
Yes. The code shows correct interaction across all states, hover the Figma Prototype has a discrepancy in the Hover, Selected and Hover + Selected states.

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
I work with the Carbon Design System. The issue isn't pressing and isn't a blocker for any work.

---

## Tasks
- [x] Update the Dropdown menu List Item across: Hover, Selected and Hover + Selected states.
- [x] Carbon review (carbon designer)
- [x] Figma review (figma expert/Juan)

**Comment by alina-jacob** [comment]
**Before vs After**


**Before:** Horizontal divider of option items was always visible in hover, selected and hover+selected states
**After:** Horizontal divider of option items is neatly dissolved across hover, selected and hover+selected states
**Note :information_source: :**This fix was achieved using a Figma workaround, the specs aren't true. Kindly refer to the website guidelines for accurate specs.

<img width="735" alt="Before vs After" src="https://github.com/carbon-design-system/carbon-design-kit/assets/159760598/0330c7f7-3a84-4fa8-8c52-1cf3f97569f8">
