### ISSUE TITLE
[AI Essentials] Create a component for Slug + Callout

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#760]
Create a component for Slug + Callout. Right now they are two separate components. We need to create a Figma component that easily allows the user to toggle the callout on from the Slug. This will help designers understand where the callout is placed in relation to the slug. 

```[tasklist]
### Tasks
- [ ] Standard slug + callout 
- [ ] Hollow slug + tooltip
- [ ] Inline slug (solid) + callout
- [ ] Inline slug (hollow) + tooltip
```

**Comment by ljcarot** [comment]
@aagonzales Can we close this issue if you made the updates in the Figma library?

**Comment by ljcarot** [comment]
@tw15egan Is this issue still relevant or can we close it out?

**Comment by aagonzales** [comment]
I think we still need to do this. Right now the Figma implementation does not match code. In Figma these are still two separate components. We need to combine these in Figma.

**Comment by ljcarot** [comment]
@aagonzales Did this update happen?
