### ISSUE TITLE
Add AI kit enhancements to the core library 🏖️ 

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#766]
Now that the AI styles are approaching stable, we feel confident that we can add the AI variants of carbon components to the core library `[v11] All themes - Carbon Design System`. Variants are currently available in the AI Essentials kit as "stickers" and need to be added to carbon to become a proper Figma component. 

Juan has done a proof of concept of how we want to implement this variant in Figma.[ Follow the text input example in this branch](https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/branch/Qy7110syO0co6TqdDpaOby/(v11)-All-themes---Carbon-Design-System?type=design&node-id=50557%3A3705&mode=design&t=exYAxrS2jO97iIUT-1). 

A few items need to be completed as pre-work before the bulk of the component work can happen. 

### Process
Create a separate branch for each component and merge the branch in the main after review approvals. This may mean AI variants get published before all are completed, but we will not announce the changes until all are done. We are doing it this way to prevent memory issues with the branch merging we have faced.

```[tasklist]
### Prework
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/761
- [x] Migrate any necessary existing AI Essentials kit component to the core library
- [x] Optimize layer component for building needs ([see Juan's notes](https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/branch/Qy7110syO0co6TqdDpaOby/(v11)-All-themes---Carbon-Design-System?type=design&node-id=395%3A4&mode=design&t=exYAxrS2jO97iIUT-1))
- [x] Document how we want to work in the branch/s in Figma for file size concerns
```

```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/770
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/777
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/773
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/779
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/778
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/780
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/774
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/776
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/771
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/772
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/795
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/775
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/781
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/784
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/787
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/788
```
