### ISSUE TITLE
[AI kit enhancements] Add AI variant of Checkbox

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#770]
Create a separate branch for each component and merge the branch in the main after review approvals. 

```[tasklist]
### Tasks
- [x] Create a separate variant for AI checkbox
- [x] Visual review by Anna or Rich
- [x] Figma review by (Juan or Rich maybe?)
```

## Design spec
[Figma file](https://www.figma.com/file/7eMfOAyRclD4LuDFwRAa3p/Carbon-for-AI-Sketches?type=design&node-id=480%3A158599&mode=design&t=FyjHN5u6hfbwM21c-1) | [Code example](https://react.carbondesignsystem.com/?path=/story/experimental-unstable-slug-examples--checkbox)
<img width="1056" alt="Checkbox spec" src="https://github.com/carbon-design-system/carbon-design-kit/assets/11670886/1866fea8-3bc3-4b9e-acb9-c3e689944ab6">
