### ISSUE TITLE
[AI kit enhancements] Add AI variant of Number input

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#772]
[AI Form input Figma Reference](https://www.figma.com/file/4aMIX5zjux2LhbW1aI3xgD/Carbon-for-AI---AI-Essentials-Kit?type=design&node-id=1371-72450&mode=design&t=wa2sPupKNGi19QxB-4)

--- 
**Tasks:**

- [x] Create **AI package** (slug + revert button + border + layer) for **Default state** across all **Sizes** (large, medium, small)
- [x] Update AI Number Input (Default + Fluid)
- [x] Review by AI Expert
- [x] Review by Figma Expert
