### ISSUE TITLE
[AI kit enhancements] Add AI variant of Radio button

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#773]
Figma link: https://www.figma.com/file/7eMfOAyRclD4LuDFwRAa3p/Carbon-for-AI-Sketches?type=design&node-id=1599-97302&mode=design

<img width="1056" alt="Radio button spec" src="https://github.com/carbon-design-system/carbon-design-kit/assets/77697351/81d41de7-1b12-4071-a14a-f5100a268357">

--- 

```[tasklist]
### Tasks
- [x] Add AI slug next to the label
- [x] Add AI slug next to the option
- [x] Review with Juan, Eugene, and Pat
```
