### ISSUE TITLE
[AI kit enhancements] Add AI variant of Date picker

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#775]
[AI Essentials Kit](https://www.figma.com/file/4aMIX5zjux2LhbW1aI3xgD/Carbon-for-AI---AI-Essentials-Kit?type=design&node-id=1371%3A72450&mode=design&t=HbbAEELqt42G9jl3-1) | [Code example](https://react.carbondesignsystem.com/?path=/story/experimental-unstable-slug-examples--date-picker)

```[tasklist]
### Tasks
- [x] Add variants for  AI present states for enabled, hover, focus, read-only, disabled, open
- [x] Add AI for sizes: sm, md, large
- [x] Add Revert back to AI state
- [x] Visual review with Anna or Rich
```
