### ISSUE TITLE
[AI kit enhancements] Add AI variant of Dropdown

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#776]
[AI Dropdown Figma Reference](https://www.figma.com/file/4aMIX5zjux2LhbW1aI3xgD/Carbon-for-AI---AI-Essentials-Kit?type=design&node-id=927-177839&mode=design&t=nyvlR7K9tSedj5RK-4)

--- 
**Tasks:**

- [x] Create **AI package** (slug + revert button + border + layer) for **Default & Fluid states** across all **Sizes** (large, medium, small)
- [x] Update AI Dropdown (Default + Fluid)
- [x] Update AI Combobox (Default + Fluid)
- [x] Update AI Multi-select (Default + Fluid)
- [x] Update AI Filterable multi-select (Default + Fluid)
- [x] Review by AI Expert
- [x] Review by Figma Expert
