### ISSUE TITLE
[AI kit enhancements] Add AI variant of Text area

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#779]
No spec 
[Storybook reference](https://react.carbondesignsystem.com/?path=/story/experimental-unstable-slug-examples--text-area)
[Figma link ](https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/branch/0sKjAwmv0Rj8trKZAEbKJW/(v11)-All-themes---Carbon-Design-System?type=design&node-id=5564%3A279849&mode=design&t=B9I5ebPPpL8q4N6K-1)

----

```[tasklist]
### Tasks
- [x] Add AI slug
- [x] Add Revert button
- [x] Add AI background
- [x] Review with Juan, Eugene, and Pat
```
