### ISSUE TITLE
[End of March!] Make an announcement + Provide tutorial

### ISSUE THREAD

**Issue by thyhmdo** [carbon-design-system/carbon-design-kit#788]
AI variables are hidden and could be challenging for average users. We need to plan to provide resources and combine this with Figma Hours to help people understand how to use them. 

```[tasklist]
### Tasks
- [x] Publish components
- [x] Make an announcement (maybe need an AI image)
- [x] Plan on how to provide tutorial
- [x] Explain this in Figma Offce hours
- [x] Provide short tutorials if needed
```
