### ISSUE TITLE
[Bug]: Data table page-nav bug

### ISSUE THREAD

**Issue by alina-jacob** [carbon-design-system/carbon-design-kit#811]
### Package

carbon-components

### Package version

V11 All Themes Figma kit

### Description

**Expected**
The Data table page-nav is supposed to look like this as per Carbon website guidelines
![Image](https://github.com/carbon-design-system/carbon/assets/159760598/67a59cc5-6152-4873-a3c5-e2878cb97bb5)

**Current**
However the Figma file has the page-nav component slightly different, this needs to be consistent across documentation. 
![Image](https://github.com/carbon-design-system/carbon/assets/159760598/b4573a16-307c-4eb6-85a6-d9887decd5d7)

### Screenshots

_Shared above_

### Steps to reproduce

**Task list** 

- [x] Unhide the "items per page" label from the page-nav component.
- [x] Update the `pagination` component because we need to adjust the spacing between "Items per page" and the page number (8px)
- [x] Update the base component in Pagination page
- [x] Check if all changes are applied to Data table
- [x] Carbon expert review
- [x] Figma expert review

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by juanencalada** [comment]
Hi @alina-jacob I reviewed this part and looks good in your branch! Great work!
