### ISSUE TITLE
[CodeSnippet - inline]: Code snippet item is nested inside of Tooltip

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-design-kit#820]
Related https://github.com/carbon-design-system/carbon/issues/16273 

- We're unable to map this component with Code Connect correctly as it is built oddly in Figma, with the code snippet item nested inside of the tooltip. 

![Screenshot 2024-05-20 at 8 49 45 AM](https://github.com/carbon-design-system/carbon-design-kit/assets/2753488/1ae4c260-14ff-4018-b721-256a7ce62253)

----

**Task**
- [ ] Make changes to the Coder snippet inline variant so it maps correctly.
- [ ] Add tooltip to hover state.

**Review**
- [ ] Carbon designer
- [ ] Figma expert
- [ ] Carbon dev (Alison)

**Comment by laurenmrice** [comment]
- Possibly we should `lock` the tooltip overflow in an absolute position so it maps correctly.
- We might need to reach out to @juanencalada and @alisonjoseph when resolving this issue.

**Comment by alisonjoseph** [comment]
No longer an issue
