### ISSUE TITLE
Figma release cadence

### ISSUE THREAD

**Issue by Kritvi-bhatia17** [carbon-design-system/carbon-design-kit#823]
## Problem
Our current approach to managing Figma releases lacks structure, resulting in challenges in effectively communicating new Figma releases.

### Description
- There is a need to establish a more structured approach to managing Figma releases. 
- This involves implementing clear processes for announcing new features, deprecating properties within components, and managing other aspects of Figma releases. 
- A structured approach will improve communication, organization, and coordination throughout the release process.
 

### Notes: 
**Initial Goal:** At the moment, we're focused on figuring out how to organize the pushing of our kits and documenting the process. We're also considering putting designers on a rotation to share this responsibility, similar to how developers do.

**Later Goal:** As we move forward, we may explore leveraging the same Slack bot currently used for dev-related announcements to organize tasks into "dev" and "design" categories.

**Comment by thyhmdo** [comment]
@Kritvi-bhatia17 Our team discussed this with Juan. I wrote down tasks but we definitely can update these tasks if we need to refine them more. We'll need to have write-out guidance for each feature on the "Read Me" page and make a monthly announcement on Slack.

**Comment by Kritvi-bhatia17** [comment]
Got it @thyhmdo, thanks for the update. Sounds good!

**Comment by thyhmdo** [comment]
### [Need to clean this up- Thinking that we can turn this Epic issue into a general announcement, including Figma and Website updates]

Summary: We’ve been tagging a growing number of issues with “needs: community contribution” on GitHub. To better support and guide contributors—a more visible and consistent communication strategy is needed across channels.

## Tasks

### Slack Communication
- [ ] Post a pinned message in relevant Slack channels (#carbon-design-system, #carbon-for-ibmproducts, #carbon-web-components, etc.  
   

  > Message (text or video) should include (refer [Carbon’s contribution guide](https://carbondesignsystem.com/contributing/get-started/overview/)):
  > - Types of contributions (code, docs, design, etc.)
  > -  Where to find issues and how to filter (labels/tags)
  > - How to get started (PDLC, Carbon Labs docs)
  > - Tools/platforms used
  > - Recognition (e.g., Carbon Champion)
  > - Also links to a dedicated page (such  [Carbon’s contribution guide](https://carbondesignsystem.com/contributing/get-started/overview/)), helping avoid the risk of outdated information.

### Documentation Updates
- [ ] Update [contributing.md](https://github.com/carbon-design-system/carbon/blob/main/.github/CONTRIBUTING.md) with the same information
- [ ] Mirror content with [Carbon’s contribution guide](https://carbondesignsystem.com/contributing/get-started/overview/) to ensure consistency



### Slack Workflow & Announcements
- [ ] Create a Box note with the Block kit template for announcements
- [ ] Update the welcome message Slack workflow for new channel members
- [ ] Include an abbreviated version in:
- Carbon Champion announcements
- Automatic office hours reminders
- New release posts

> [!NOTE]
>  Links to a dedicated page (such  [Carbon’s contribution guide](https://carbondesignsystem.com/contributing/get-started/overview/)), helping avoid the risk of outdated information.

**Comment by Kritvi-bhatia17** [comment]
> [Need to clean this up- Thinking that we can turn this Epic issue into a general announcement, including Figma and Website updates]
> .
> .
> Links to a dedicated page (such [Carbon’s contribution guide](https://carbondesignsystem.com/contributing/get-started/overview/)), helping avoid the risk of outdated information.

This looks great, @thyhmdo! Just wanted to confirm—does the issue you mentioned also include [this issue](https://github.com/carbon-design-system/carbon-design-kit/issues/922#issue-3066080470) i.e. 'announcement behavior in Figma'? Wondering if that could be considered within the scope as well.
