### ISSUE TITLE
[Prototyping]: add more functionality to dropdown and menu button

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-design-kit#828]
## Detailed description

- In office hours, we received feedback that when teams prototype with our components, not all of them are fully functional, especially some that are used frequently.
- Enhance Dropdown and Menu button in the Figma kit to include more prototyping functionality. 

---

### Tasks

**Dropdown (default style)**
- [ ] Menu does not display when selected

**Menu button**
- [ ] Button menu does not display when the button is selected in the prototype
- [ ] The menu contents I’ve input into the menu is not retained after closing the file and reopening
- [ ] Rollover effects are present

### Review
- [ ] Carbon
- [ ] Figma
