### ISSUE TITLE
[Badge indicator] Add to Figma

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-design-kit#865]
## Acceptance criteria

**Tasks**
- [x] Add the badge indicator to the UI Shell header action buttons 
- [x] Add the badge indicator to the buttons (mostly ghost button–but will wait to see how devs implement this)
- [x] Add the badge indicator to TreeView
- [x] Add the badge indicator to Tabs 

**Review**
- [x] Carbon designer
- [x] Figma expert

**Comment by sstrubberg** [comment]
Blocked until implementation is complete.

**Comment by thyhmdo** [comment]
Ready to merge when the code is implemented
