### ISSUE TITLE
[Dropdown, Combobox & Multiselect]: Update Figma kit focus states

### ISSUE THREAD

**Issue by Kritvi-bhatia17** [carbon-design-system/carbon-design-kit#874]
## Acceptance criteria
**Background**: Michael highlighted some differences in interaction and behavior across several Dropdown variants, including Combobox, Multiselect, Filterable Multiselect, Multiselect with Select All, and Fluid Dropdown with no default option. Specifically, a few of the focus states need adjustments. We discussed this further in the [CAG call (Oct 21)](https://ibm-my.sharepoint.com/personal/michael_gower_ca_ibm_com/_layouts/15/stream.aspx?id=/personal/michael_gower_ca_ibm_com/Documents/Recordings/Carbon+Accessibility+Guild-20241021_070259-Meeting+Recording.mp4).

### Tasks
- [x] Update the focus states in the Figma kit based on [this](https://www.figma.com/design/xHzG8VCEAXXJnV0GAzcj44/Dropdown?node-id=287-28973&t=cKkE7YN1s6CKOynl-4) (reviewed by Michael) , prioritizing mouse/Enter key interactions, as these are most commonly used.
- [x] Fix the placeholder value bugs in some places

#### Review
- [x] Accessibility expert (Michael)
- [x] Carbon designer (Lauren)

--- 

- [x] Additionally, create an issue to update Storybook to reflect both mouse/Enter key interactions and Down Arrow keyboard interactions.
